[package]
name = "rust-ip-lookup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
text-to-ascii-art = "0.1.10"
tokio = { version = "1.45.0", features = ["full"] }
trust-dns-resolver = "0.23.2"
